/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Uygulama;

import static Uygulama.Login.k_adi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joglen20
 */
public class Direktorluk extends javax.swing.JFrame {

    DB db = new DB("bankasistemi", "root", "");
     ButtonGroup brg=new ButtonGroup();
    /**
     * Creates new form direktorluk
     */

    public Direktorluk() {
        initComponents();
        mudur_Getir();
      //  listele();
        sube_List();
            brg.add(cKredi);
        brg.add(cKrediKarti);
        brg.add(paraGiris);
        brg.add(paraCikis);
        brg.add(cMusteri);
        cKredi.setSelected(true);
        txtMusteri.setVisible(false);
    }

    public void listele() {
        try {

            ResultSet rss = db.baglan().executeQuery("call List()");

            while (rss.next()) {

          
            }

        } catch (Exception e) {
            System.out.println("Data Getirme Hatası " + e);
        } finally {
            db.kapat();
        }
    }

    public void sube_List() {
        try {

            ResultSet rss = db.baglan().executeQuery("call sube_List()");

            while (rss.next()) {
                String gecici = rss.getString("sube_adi");
                comboSube.addItem(gecici);

            }

        } catch (Exception e) {
            System.out.println("Data Getirme Hatası " + e);
        } finally {
            db.kapat();
        }
    }

    public void mudur_Getir() {
        try {

            ResultSet rss = db.baglan().executeQuery("call mudur_Getir()");
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Kullanici Adi");

            while (rss.next()) {

                dtm.addRow(new String[]{rss.getString("kadi")});

            }
            jTable1.setModel(dtm);
        } catch (Exception e) {
            System.out.println("Data Getirme Hatası " + e);
        } finally {
            db.kapat();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtMdrAdi = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        pswMdrSifre = new javax.swing.JPasswordField();
        comboSube = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        txtAra = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtSubeAdi = new javax.swing.JTextField();
        txtSubeKod = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        cKredi = new javax.swing.JRadioButton();
        cKrediKarti = new javax.swing.JRadioButton();
        paraGiris = new javax.swing.JRadioButton();
        paraCikis = new javax.swing.JRadioButton();
        cMusteri = new javax.swing.JRadioButton();
        jPanel61 = new javax.swing.JPanel();
        txtMusteri = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        jButton27 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        pswEskiSifre = new javax.swing.JPasswordField();
        pswYeniSifre = new javax.swing.JPasswordField();
        sifreonay = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DIREKTORLUK");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Mudur Ekle"));

        jLabel8.setText("Gorevi");

        jLabel9.setText("Gecici Sifre");

        jButton3.setText("Ekle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mudur" }));

        jLabel10.setText("Subesi");

        jLabel7.setText("Kullanici Adi");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 27, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMdrAdi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 130, Short.MAX_VALUE)
                    .addComponent(pswMdrSifre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(comboSube, javax.swing.GroupLayout.Alignment.TRAILING, 0, 130, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMdrAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(pswMdrSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(comboSube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Müdür Listesi"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanıcılar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("ARA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("SIL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("YENILE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                        .addComponent(txtAra, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addGap(18, 18, 18)
                .addComponent(txtAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Müdürlük İşlemleri", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Şube İşlemleri"));

        jButton2.setText("EKLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("SUBE ADI");

        jLabel5.setText("SUBE KODU");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(66, 66, 66)
                            .addComponent(txtSubeKod, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSubeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubeKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Şube Yönetimi", jPanel1);

        jPanel55.setBorder(javax.swing.BorderFactory.createTitledBorder("Raporlar"));

        cKredi.setText("Kredi Bazlı");
        cKredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKrediActionPerformed(evt);
            }
        });

        cKrediKarti.setText("Kredi Kartı Bazlı");
        cKrediKarti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKrediKartiActionPerformed(evt);
            }
        });

        paraGiris.setText("Para Giriş");
        paraGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraGirisActionPerformed(evt);
            }
        });

        paraCikis.setText("Para Çıkış");
        paraCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraCikisActionPerformed(evt);
            }
        });

        cMusteri.setText("Müşteri Bazlı");
        cMusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMusteriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMusteri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel61Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        date1.setDateFormatString("yyyy-MM-dd"); // NOI18N

        date2.setDateFormatString("yyyy-MM-dd");

        jButton27.setText("Rapor Al");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jLabel50.setText("Başlangıç Tarihi");

        jLabel51.setText("Bitiş Tarihi");

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paraGiris)
                            .addComponent(cKrediKarti)
                            .addComponent(cKredi)
                            .addComponent(paraCikis)
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addComponent(cMusteri)
                                .addGap(31, 31, 31)
                                .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addComponent(cKredi)
                        .addGap(18, 18, 18)
                        .addComponent(cKrediKarti)
                        .addGap(18, 18, 18)
                        .addComponent(paraGiris)
                        .addGap(18, 18, 18)
                        .addComponent(paraCikis)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cMusteri)
                            .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel50))
                .addGap(20, 20, 20)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel51)
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton27)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri Adı", "Hesap Türü", "Bakiye", "Tarih"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane11.setViewportView(jTable11);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Raporlar", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Hesap Yönetimi"));

        jButton1.setText("DEGISTIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Şifre");

        jLabel2.setText("Yeni Şifre");

        jLabel3.setText("Onay");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sifreonay, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(pswYeniSifre)
                            .addComponent(pswEskiSifre, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 109, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswEskiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswYeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreonay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hesap Yönetimi", jPanel4);

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Çıkış", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            System.out.println(k_adi);
            String q = "call p_Sifre('" + k_adi + "')";
            ResultSet rss = db.baglan().executeQuery(q);
            String Sifre = null;
            while (rss.next()) {
                Sifre = rss.getString(1);
                System.out.println(Sifre);
            }
            String yenisifre = pswYeniSifre.getText();
            String onay = sifreonay.getText();
            String eskiSifre = pswEskiSifre.getText();
            if (Sifre.equalsIgnoreCase("") || yenisifre.equalsIgnoreCase("") || onay.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(rootPane, "Sifre alanlari bos  olamaz! ");
            } else if (!eskiSifre.equalsIgnoreCase(Sifre)) {
                JOptionPane.showMessageDialog(rootPane, "Gerekli alanlar bos eksik ya da hatali");
                pswYeniSifre.setText("");
                sifreonay.setText("");
                pswEskiSifre.setText("");
            } else if (!yenisifre.equalsIgnoreCase(onay)) {
                JOptionPane.showMessageDialog(rootPane, "onay sifreleri uyumsuz");
                pswYeniSifre.setText("");
                sifreonay.setText("");
                pswEskiSifre.setText("");
            } else {
                System.out.println(k_adi);
                System.out.println(yenisifre);
                String updateQuery = "call sifre_Islemleri('" + yenisifre + "','" + k_adi + "')";
                int yazSonuc = db.baglan().executeUpdate(updateQuery);
                if (yazSonuc > 0) {

                    JOptionPane.showMessageDialog(rootPane, "Update işlemi başarılı");
                    pswYeniSifre.setText("");
                    sifreonay.setText("");
                    pswEskiSifre.setText("");
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

   

        String query = "call sube_kayit(?,?)";
        PreparedStatement prr = db.preBaglan(query);
        try {
            prr.setString(1, txtSubeKod.getText().trim());
            prr.setString(2, txtSubeAdi.getText().trim());
        
            prr.execute();
            JOptionPane.showMessageDialog(rootPane, "kayit islemi basarili");

            mudur_Getir();

            txtSubeKod.setText("");
            txtSubeAdi.setText("");

        } catch (SQLException ex) {
            System.out.println(ex);
        }        // TODO add your handling code here:


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked

        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        int dialogButton = 0;
        int x = jTabbedPane1.getSelectedIndex();

        if (x == 4) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Cikmak istediginize emin misiniz?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {

                dispose();

            }
    }//GEN-LAST:event_jTabbedPane1MouseClicked
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
             ResultSet rss = db.baglan().executeQuery("call personel_VarMi('"+txtMdrAdi.getText()+"')");
              while(rss.next()){
                   if(rss.getString(1).equals("1")){
                   JOptionPane.showMessageDialog(rootPane, "Kullanici daha once olusturuldu"); 
                   pswMdrSifre.setText("");
            txtMdrAdi.setText("");
               }
                   else{
                      String adi = txtMdrAdi.getText();
        String gorevi = jComboBox2.getItemAt(0).toString();

        String Sifre = pswMdrSifre.getText();

        String query = "call mudur_Kaydet(?,?,?,?)";
        PreparedStatement prr = db.preBaglan(query);
        
            prr.setString(1, txtMdrAdi.getText().trim());
            prr.setString(2, pswMdrSifre.getText().trim());
            prr.setString(3, "mdr");
            prr.setString(4, comboSube.getSelectedItem().toString());
            prr.execute();
            JOptionPane.showMessageDialog(rootPane, "kayit islemi basarili");

            mudur_Getir();
            txtMdrAdi.setText("");
            pswMdrSifre.setText("");
  
                   }
        }} catch (Exception e) {
        }
       
           
               
          
        
       
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txtAra.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Aranacak deger belirleyiniz");
            txtAra.requestFocus();

        } else {
            try {
                String q = "call mudur_Ara('" + txtAra.getText().trim() + "')";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();
                dtm.addColumn("Kullanici Adi");

                while (rss.next()) {

                    dtm.addRow(new String[]{rss.getString(1)});
                    System.out.println(rss.getString(1));
                }
                jTable1.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int dialogButton = 0;

        int dialogResult = JOptionPane.showConfirmDialog(null, "Silmek istediginize emin misiniz?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            int row = jTable1.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(rootPane, "Silmek icin kullanici seciniz!");
            } else {
                // silme işlemini yap
                try {

                    String silQuery = "call mudur_Sil('" + jTable1.getValueAt(row, 0) + "')";

                    int silSonuc = db.baglan().executeUpdate(silQuery);
                    if (silSonuc > 0) {
                        mudur_Getir();

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Silme hatası !");
                    }
                } catch (Exception e) {
                    System.err.println("Silme hatası : " + e);
                }
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        mudur_Getir();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cKrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKrediActionPerformed
        jPanel61.setVisible(false);
    }//GEN-LAST:event_cKrediActionPerformed

    private void cKrediKartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKrediKartiActionPerformed
        jPanel61.setVisible(false);
    }//GEN-LAST:event_cKrediKartiActionPerformed

    private void paraGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraGirisActionPerformed
        jPanel61.setVisible(false);
    }//GEN-LAST:event_paraGirisActionPerformed

    private void paraCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraCikisActionPerformed
        jPanel61.setVisible(false);
    }//GEN-LAST:event_paraCikisActionPerformed

    private void cMusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMusteriActionPerformed
        jPanel61.setVisible(true);
    }//GEN-LAST:event_cMusteriActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed

        if (cKredi.isSelected()) {
            try {
                String q = "call krediKartiRapor()";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Kredi  Miktari");
                dtm.addColumn("Gelir Durumu");
                dtm.addColumn("Durum");

                while (rss.next()) {
                    String gecici = rss.getString(5).toString().trim();
                    if (gecici.equals("2")) {
                        gecici = "Onaylandi";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), rss.getString(4), gecici});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }
        } else if (cKrediKarti.isSelected()) {
            try {
                String q = "call krediRapor()";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Kredi Karti  Miktari");
                dtm.addColumn("Gelir Durumu");
                dtm.addColumn("Durum");

                while (rss.next()) {
                    String gecici = rss.getString(5).toString().trim();
                    if (gecici.equals("2")) {
                        gecici = "Onaylandi";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), rss.getString(4), gecici});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        } else if (cMusteri.isSelected()) {

            if (!txtMusteri.getText().equals("")) {
                try {
                    String q = "call musteriRapor('" + txtMusteri.getText() + "')";
                    ResultSet rss = db.baglan().executeQuery(q);
                    DefaultTableModel dtm = new DefaultTableModel();

                    dtm.addColumn("Adi");
                    dtm.addColumn("Soyadi");
                    dtm.addColumn("Bakiye");
                    dtm.addColumn("Doviz Tipi");

                    while (rss.next()) {
                        String gecici = rss.getString(4).toString().trim();
                        if (gecici.equals("1")) {
                            gecici = "TL";
                        } else if (gecici.equals("2")) {
                            gecici = "Dolar";
                        } else if (gecici.equals("3")) {
                            gecici = "Euro";
                        } else if (gecici.equals("4")) {
                            gecici = "Sterlin";
                        }
                        dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), gecici});

                    }
                    jTable11.setModel(dtm);
                } catch (Exception e) {
                    System.out.println("Data Getirme Hatası " + e);
                } finally {
                    db.kapat();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Musteri adi giriniz");
            }

        } else if (paraGiris.isSelected()) {
            try {
                String q = "call hesapGiris()";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Bakiye");
                dtm.addColumn("Doviz Tipi");
                dtm.addColumn("Islem Turu");

                while (rss.next()) {
                    String gecici2 = rss.getString(5).toString().trim();
                    String gecici = rss.getString(4).toString().trim();
                    if (gecici.equals("1")) {
                        gecici = "TL";
                    } else if (gecici.equals("2")) {
                        gecici = "Dolar";
                    } else if (gecici.equals("3")) {
                        gecici = "Euro";
                    } else if (gecici.equals("4")) {
                        gecici = "Sterlin";
                    }
                    if (gecici2.equals("1")) {
                        gecici2 = "Giris";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), gecici, gecici2});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        } else if (paraCikis.isSelected()) {
            try {
                String q = "call hesapCikis()";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Bakiye");
                dtm.addColumn("Doviz Tipi");
                dtm.addColumn("Islem Turu");

                while (rss.next()) {
                    String gecici2 = rss.getString(5).toString().trim();
                    String gecici = rss.getString(4).toString().trim();
                    if (gecici.equals("1")) {
                        gecici = "TL";
                    } else if (gecici.equals("2")) {
                        gecici = "Dolar";
                    } else if (gecici.equals("3")) {
                        gecici = "Euro";
                    } else if (gecici.equals("4")) {
                        gecici = "Sterlin";
                    }
                    if (gecici2.equals("2")) {
                        gecici2 = "Cikis";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), gecici, gecici2});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        } else {
            try {

                Date d1 = date1.getDate();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                System.out.println(df.format(d1));
                Date d2 = date2.getDate();

                System.out.println(df.format(d2));

                String q = "call dateRapor('" + df.format(d1) + "','" + df.format(d2) + "')";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Bakiye");
                dtm.addColumn("Doviz Tipi");
                dtm.addColumn("Islem Turu");
                dtm.addColumn("Islem Tarihi");

                while (rss.next()) {
                    String gecici2 = rss.getString(5).toString().trim();
                    String gecici = rss.getString(4).trim();
                    if (gecici.equals("1")) {
                        gecici = "TL";
                    } else if (gecici.equals("2")) {
                        gecici = "Dolar";
                    } else if (gecici.equals("3")) {
                        gecici = "Euro";
                    } else if (gecici.equals("4")) {
                        gecici = "Sterlin";
                    }
                    if (gecici2.equals("2")) {
                        gecici2 = "Cikis";
                    } else if (gecici2.equals("1")) {
                        gecici2 = "Giris";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), gecici, gecici2, rss.getString(6)});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        }
    }//GEN-LAST:event_jButton27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Direktorluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Direktorluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Direktorluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Direktorluk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Direktorluk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cKredi;
    private javax.swing.JRadioButton cKrediKarti;
    private javax.swing.JRadioButton cMusteri;
    private javax.swing.JComboBox<String> comboSube;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable11;
    private javax.swing.JRadioButton paraCikis;
    private javax.swing.JRadioButton paraGiris;
    private javax.swing.JPasswordField pswEskiSifre;
    private javax.swing.JPasswordField pswMdrSifre;
    private javax.swing.JPasswordField pswYeniSifre;
    private javax.swing.JPasswordField sifreonay;
    private javax.swing.JTextField txtAra;
    private javax.swing.JTextField txtMdrAdi;
    private javax.swing.JTextField txtMusteri;
    private javax.swing.JTextField txtSubeAdi;
    private javax.swing.JTextField txtSubeKod;
    // End of variables declaration//GEN-END:variables
}
