package Uygulama;

import static Uygulama.Login.k_adi;
import com.toedter.calendar.JDateChooser;
import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joglen20
 */
public class Mudur extends javax.swing.JFrame {

    DB db = new DB("bankasistemi", "root", "");
        ButtonGroup brg=new ButtonGroup();

    public static String OnayId;

    /**
     * Creates new form Mudur
     */
    public void sube_List() {
        try {
           jPanel61.setVisible(false);
            ResultSet rss = db.baglan().executeQuery("call sube_List()");

            while (rss.next()) {
                String gecici = rss.getString("sube_adi");
                comboSube.addItem(gecici);

            }

        } catch (Exception e) {
            System.out.println("Data Getirme Hatası " + e);
        } finally {
            db.kapat();
        }
    }

    public void krediList() {
        try {
            String q = "call kk_List()";
            ResultSet rss = db.baglan().executeQuery(q);
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Onay ID");
            dtm.addColumn("Adi");
            dtm.addColumn("Soyadi");
            dtm.addColumn("Kredi Miktari");
            dtm.addColumn("Gelir Durumu");
            dtm.addColumn("Durum");

            while (rss.next()) {
                String gecici = rss.getString(5).toString().trim();
                if (gecici.equals("1")) {
                    gecici = "Beklemede";
                }
                dtm.addRow(new String[]{rss.getString(6), rss.getString(1), rss.getString(2), rss.getString(3), rss.getString(4), gecici});
                OnayId = rss.getString(6);
                System.out.println(OnayId);
            }
            jTable2.setModel(dtm);
        } catch (Exception e) {
            System.out.println("Data Getirme Hatası " + e);
        } finally {
            db.kapat();
        }
    }

    public void dataGetir() {

        try {

            ResultSet rss = db.baglan().executeQuery("call data_Getir()");
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Kullanici Adi");

            while (rss.next()) {

                dtm.addRow(new String[]{rss.getString(1)});

            }
            jTable1.setModel(dtm);
        } catch (Exception e) {
            System.out.println("Data Getirme Hatası " + e);
        }
    }

    public Mudur() {
        initComponents();
        dataGetir();
        krediList();
        sube_List();
            brg.add(cKredi);
        brg.add(cKrediKarti);
        brg.add(paraGiris);
        brg.add(paraCikis);
        brg.add(cMusteri);
        cKredi.setSelected(true);
        txtMusteri.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adi = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        PersonelEkle = new javax.swing.JPanel();
        txtAdi = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        comboSube = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        txtAra = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        cKredi = new javax.swing.JRadioButton();
        cKrediKarti = new javax.swing.JRadioButton();
        paraGiris = new javax.swing.JRadioButton();
        paraCikis = new javax.swing.JRadioButton();
        cMusteri = new javax.swing.JRadioButton();
        jPanel61 = new javax.swing.JPanel();
        txtMusteri = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        jButton27 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        pswEskiSifre = new javax.swing.JPasswordField();
        pswYeniSifre = new javax.swing.JPasswordField();
        sifreonay = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        Adi.setText("label1");

        jLabel1.setText("jLabel1");

        label2.setText("label2");

        jLabel7.setText("jLabel7");

        jCheckBox1.setText("jCheckBox1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MUDURLUK");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton6.setText("Olumlu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Olumsuz");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setText("yenile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(jButton1))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Onay İşlemler", jPanel1);

        PersonelEkle.setBorder(javax.swing.BorderFactory.createTitledBorder("Personel Ekle"));

        jButton3.setText("EKLE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Kullanıcı Adı");

        jLabel9.setText("Görevi");

        jLabel11.setText("Geçici Şifre");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gise Gorevlisi" }));

        jLabel3.setText("Şubesi");

        javax.swing.GroupLayout PersonelEkleLayout = new javax.swing.GroupLayout(PersonelEkle);
        PersonelEkle.setLayout(PersonelEkleLayout);
        PersonelEkleLayout.setHorizontalGroup(
            PersonelEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonelEkleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonelEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(PersonelEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboSube, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonelEkleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PersonelEkleLayout.setVerticalGroup(
            PersonelEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonelEkleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PersonelEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonelEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PersonelEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PersonelEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboSube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Personel Listesi"));

        jButton4.setText("Ara");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtAra.setText(" ");

        jButton5.setText("Sil");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanıcılar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton7.setText("Yenile");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAra, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addGap(18, 18, 18)
                .addComponent(txtAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PersonelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PersonelEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Veznedar Yönetimi", jPanel3);

        jPanel55.setBorder(javax.swing.BorderFactory.createTitledBorder("Raporlar"));

        cKredi.setText("Kredi Bazlı");
        cKredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKrediActionPerformed(evt);
            }
        });

        cKrediKarti.setText("Kredi Kartı Bazlı");
        cKrediKarti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cKrediKartiActionPerformed(evt);
            }
        });

        paraGiris.setText("Para Giriş");
        paraGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraGirisActionPerformed(evt);
            }
        });

        paraCikis.setText("Para Çıkış");
        paraCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraCikisActionPerformed(evt);
            }
        });

        cMusteri.setText("Müşteri Bazlı");
        cMusteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMusteriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMusteri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel61Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtMusteri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        date1.setDateFormatString("yyyy-MM-dd"); // NOI18N

        date2.setDateFormatString("yyyy-MM-dd");

        jButton27.setText("Rapor Al");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jLabel50.setText("Başlangıç Tarihi");

        jLabel51.setText("Bitiş Tarihi");

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paraGiris)
                            .addComponent(cKrediKarti)
                            .addComponent(cKredi)
                            .addComponent(paraCikis)
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel55Layout.createSequentialGroup()
                                .addComponent(cMusteri)
                                .addGap(31, 31, 31)
                                .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel55Layout.createSequentialGroup()
                        .addComponent(cKredi)
                        .addGap(18, 18, 18)
                        .addComponent(cKrediKarti)
                        .addGap(18, 18, 18)
                        .addComponent(paraGiris)
                        .addGap(18, 18, 18)
                        .addComponent(paraCikis)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cMusteri)
                            .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel50))
                .addGap(20, 20, 20)
                .addGroup(jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel51)
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton27)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri Adı", "Hesap Türü", "Bakiye", "Tarih"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane11.setViewportView(jTable11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Raporlar", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Hesap Yönetimi"));

        jButton2.setText("DEGISTIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Eski Sifre");

        jLabel13.setText("Yeni Sifre");

        jLabel14.setText("Yeni Sifre Onay");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(pswYeniSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(pswEskiSifre)
                    .addComponent(sifreonay))
                .addGap(25, 25, 25))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswEskiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswYeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreonay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hesap Yönetimi", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Çıkış", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            ResultSet rss = db.baglan().executeQuery("call personel_VarMi('"+txtAdi.getText()+"')");
           
               
           while(rss.next()){
                   if(rss.getString(1).equals("1")){
                   JOptionPane.showMessageDialog(rootPane, "Kullanici daha once olusturuldu"); 
                   txtSifre.setText("");
            txtAdi.setText("");
               }
           
               
               else{
                  String adi = txtAdi.getText();
        
        String gorevi = jComboBox3.getItemAt(0).toString();

        String Sifre = txtSifre.getText();

        String query = "call p_kaydet(?,?,?,?)";
        PreparedStatement prr = db.preBaglan(query);
    
            prr.setString(1, txtAdi.getText().trim());
            prr.setString(2, txtSifre.getText().trim());
            prr.setString(3, "vzn");
            prr.setString(4, comboSube.getSelectedItem().toString());
            prr.execute();
            JOptionPane.showMessageDialog(rootPane, "kayit islemi basarili");

            dataGetir();
            txtSifre.setText("");
            txtAdi.setText("");
    
                   }
               }
           
            }
        catch (SQLException ex) {
            System.out.println(ex);
        }
      


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int dialogButton = 0;

        int dialogResult = JOptionPane.showConfirmDialog(null, "Silmek istediginize emin misiniz?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            int row = jTable1.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(rootPane, "Silmek icin kullanici seciniz!");
            } else {
                // silme işlemini yap
                try {

                    String silQuery = "call personel_Sil('" + jTable1.getValueAt(row, 0) + "')";

                    int silSonuc = db.baglan().executeUpdate(silQuery);
                    if (silSonuc > 0) {
                        dataGetir();

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Silme hatası !");
                    }
                } catch (Exception e) {
                    System.err.println("Silme hatası : " + e);
                }
            }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dataGetir();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txtAra.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Aranacak deger belirleyiniz");
            txtAra.requestFocus();

        } else {
            try {
                String q = "call p_Ara('" + txtAra.getText().trim() + "')";
                ResultSet rss = db.baglan().executeQuery(q);
               
                DefaultTableModel dtm = new DefaultTableModel();
                dtm.addColumn("Kullanici Adi");

                while (rss.next()) {
              
                    dtm.addRow(new String[]{rss.getString(1)});
                    System.out.println(rss.getString(1));
                   
                }
                jTable1.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

    }//GEN-LAST:event_jButton4ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            String q = "call p_Sifre('" + k_adi + "')";
            ResultSet rss = db.baglan().executeQuery(q);
            String Sifre = null;
            while (rss.next()) {
                Sifre = rss.getString(1);
                System.out.println(Sifre);
            }
            String yenisifre = pswYeniSifre.getText();
            String onay = sifreonay.getText();
            String eskiSifre = pswEskiSifre.getText();
            if (Sifre.equalsIgnoreCase("") || yenisifre.equalsIgnoreCase("") || onay.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(rootPane, "Sifre alanlari bos  olamaz! ");
            } else if (!eskiSifre.equalsIgnoreCase(Sifre)) {
                JOptionPane.showMessageDialog(rootPane, "Gerekli alanlar bos eksik ya da hatali");
                pswYeniSifre.setText("");
                sifreonay.setText("");
                pswEskiSifre.setText("");
            } else if (!yenisifre.equalsIgnoreCase(onay)) {
                JOptionPane.showMessageDialog(rootPane, "onay sifreleri uyumsuz");
                pswYeniSifre.setText("");
                sifreonay.setText("");
                pswEskiSifre.setText("");
            } else {

                String updateQuery = "call sifre_Islemleri('" + yenisifre + "','" + k_adi + "')";
                int yazSonuc = db.baglan().executeUpdate(updateQuery);
                if (yazSonuc > 0) {

                    JOptionPane.showMessageDialog(rootPane, "Update işlemi başarılı");
                    pswYeniSifre.setText("");
                    sifreonay.setText("");
                    pswEskiSifre.setText("");
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

        int dialogButton = 0;
        int x = jTabbedPane1.getSelectedIndex();

        if (x == 4) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Cikmak istediginize emin misiniz?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {

                dispose();

            }
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, "Onaylamak icin musteri seciniz!");
        } else {

            try {

                String silQuery = "call Onaylat('" + jTable2.getValueAt(row, 0) + "')";

                int updateSonuc = db.baglan().executeUpdate(silQuery);
                if (updateSonuc > 0) {
                    krediList();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Update hatası !");
                }
            } catch (Exception e) {
                System.err.println("Update hatası : " + e);
            }
    }//GEN-LAST:event_jButton6ActionPerformed
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(rootPane, " Musteri seciniz!");
        } else {

            try {

                String silQuery = "call Onaylama('" + jTable2.getValueAt(row, 0) + "')";

                int updateSonuc = db.baglan().executeUpdate(silQuery);
                if (updateSonuc > 0) {
                    krediList();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Update hatası !");
                }
            } catch (Exception e) {
                System.err.println("Update hatası : " + e);
            }
    }//GEN-LAST:event_jButton8ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        krediList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cKrediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKrediActionPerformed
        jPanel61.setVisible(false);
    }//GEN-LAST:event_cKrediActionPerformed

    private void cKrediKartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cKrediKartiActionPerformed
        jPanel61.setVisible(false);
    }//GEN-LAST:event_cKrediKartiActionPerformed

    private void paraGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraGirisActionPerformed
        jPanel61.setVisible(false);
    }//GEN-LAST:event_paraGirisActionPerformed

    private void paraCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraCikisActionPerformed
        jPanel61.setVisible(false);
    }//GEN-LAST:event_paraCikisActionPerformed

    private void cMusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMusteriActionPerformed
        jPanel61.setVisible(true);
    }//GEN-LAST:event_cMusteriActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed

        if (cKredi.isSelected()) {
            try {
                String q = "call krediKartiRapor()";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Kredi  Miktari");
                dtm.addColumn("Gelir Durumu");
                dtm.addColumn("Durum");

                while (rss.next()) {
                    String gecici = rss.getString(5).toString().trim();
                    if (gecici.equals("2")) {
                        gecici = "Onaylandi";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), rss.getString(4), gecici});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }
        } else if (cKrediKarti.isSelected()) {
            try {
                String q = "call krediRapor()";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Kredi Karti  Miktari");
                dtm.addColumn("Gelir Durumu");
                dtm.addColumn("Durum");

                while (rss.next()) {
                    String gecici = rss.getString(5).toString().trim();
                    if (gecici.equals("2")) {
                        gecici = "Onaylandi";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), rss.getString(4), gecici});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        } else if (cMusteri.isSelected()) {

            if (!txtMusteri.getText().equals("")) {
                try {
                    String q = "call musteriRapor('" + txtMusteri.getText() + "')";
                    ResultSet rss = db.baglan().executeQuery(q);
                    DefaultTableModel dtm = new DefaultTableModel();

                    dtm.addColumn("Adi");
                    dtm.addColumn("Soyadi");
                    dtm.addColumn("Bakiye");
                    dtm.addColumn("Doviz Tipi");

                    while (rss.next()) {
                        String gecici = rss.getString(4).toString().trim();
                        if (gecici.equals("1")) {
                            gecici = "TL";
                        } else if (gecici.equals("2")) {
                            gecici = "Dolar";
                        } else if (gecici.equals("3")) {
                            gecici = "Euro";
                        } else if (gecici.equals("4")) {
                            gecici = "Sterlin";
                        }
                        dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), gecici});

                    }
                    jTable11.setModel(dtm);
                } catch (Exception e) {
                    System.out.println("Data Getirme Hatası " + e);
                } finally {
                    db.kapat();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Musteri adi giriniz");
            }

        } else if (paraGiris.isSelected()) {
            try {
                String q = "call hesapGiris()";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Bakiye");
                dtm.addColumn("Doviz Tipi");
                dtm.addColumn("Islem Turu");

                while (rss.next()) {
                    String gecici2 = rss.getString(5).toString().trim();
                    String gecici = rss.getString(4).toString().trim();
                    if (gecici.equals("1")) {
                        gecici = "TL";
                    } else if (gecici.equals("2")) {
                        gecici = "Dolar";
                    } else if (gecici.equals("3")) {
                        gecici = "Euro";
                    } else if (gecici.equals("4")) {
                        gecici = "Sterlin";
                    }
                    if (gecici2.equals("1")) {
                        gecici2 = "Giris";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), gecici, gecici2});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        } else if (paraCikis.isSelected()) {
            try {
                String q = "call hesapCikis()";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Bakiye");
                dtm.addColumn("Doviz Tipi");
                dtm.addColumn("Islem Turu");

                while (rss.next()) {
                    String gecici2 = rss.getString(5).toString().trim();
                    String gecici = rss.getString(4).toString().trim();
                    if (gecici.equals("1")) {
                        gecici = "TL";
                    } else if (gecici.equals("2")) {
                        gecici = "Dolar";
                    } else if (gecici.equals("3")) {
                        gecici = "Euro";
                    } else if (gecici.equals("4")) {
                        gecici = "Sterlin";
                    }
                    if (gecici2.equals("2")) {
                        gecici2 = "Cikis";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), gecici, gecici2});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        } else {
            try {

                Date d1 = date1.getDate();
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                System.out.println(df.format(d1));
                Date d2 = date2.getDate();

                System.out.println(df.format(d2));

                String q = "call dateRapor('" + df.format(d1) + "','" + df.format(d2) + "')";
                ResultSet rss = db.baglan().executeQuery(q);
                DefaultTableModel dtm = new DefaultTableModel();

                dtm.addColumn("Adi");
                dtm.addColumn("Soyadi");
                dtm.addColumn("Bakiye");
                dtm.addColumn("Doviz Tipi");
                dtm.addColumn("Islem Turu");
                dtm.addColumn("Islem Tarihi");

                while (rss.next()) {
                    String gecici2 = rss.getString(5).toString().trim();
                    String gecici = rss.getString(4).trim();
                    if (gecici.equals("1")) {
                        gecici = "TL";
                    } else if (gecici.equals("2")) {
                        gecici = "Dolar";
                    } else if (gecici.equals("3")) {
                        gecici = "Euro";
                    } else if (gecici.equals("4")) {
                        gecici = "Sterlin";
                    }
                    if (gecici2.equals("2")) {
                        gecici2 = "Cikis";
                    } else if (gecici2.equals("1")) {
                        gecici2 = "Giris";
                    }
                    dtm.addRow(new String[]{rss.getString(1), rss.getString(2), rss.getString(3), gecici, gecici2, rss.getString(6)});

                }
                jTable11.setModel(dtm);
            } catch (Exception e) {
                System.out.println("Data Getirme Hatası " + e);
            } finally {
                db.kapat();
            }

        }
    }//GEN-LAST:event_jButton27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mudur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mudur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mudur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mudur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mudur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Adi;
    private javax.swing.JPanel PersonelEkle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cKredi;
    private javax.swing.JRadioButton cKrediKarti;
    private javax.swing.JRadioButton cMusteri;
    private javax.swing.JComboBox<String> comboSube;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable2;
    private java.awt.Label label2;
    private javax.swing.JRadioButton paraCikis;
    private javax.swing.JRadioButton paraGiris;
    private javax.swing.JPasswordField pswEskiSifre;
    private javax.swing.JPasswordField pswYeniSifre;
    private javax.swing.JPasswordField sifreonay;
    private javax.swing.JTextField txtAdi;
    private javax.swing.JTextField txtAra;
    private javax.swing.JTextField txtMusteri;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
